name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: redminedb
          POSTGRES_USER: admin_for_redmine
          POSTGRES_PASSWORD: redmine
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

    steps:
      - name: Check env
        run: echo ${{ secrets.SECRET_KEY_BASE }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10

      - name: Install Bundler
        run: gem install bundler:2.2.29

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3 --without development test

      - name: Database Setup
        env:
          DB_HOST: db
          DB_PORT: 5432
          DB_NAME: redminedb
          DB_USER: admin_for_redmine
          DB_PASSWORD: redmine
        run: bundle exec rails db:create db:migrate RAILS_ENV=production

      - name: Build and Push Docker Image
        env:
          GITHUB_TOKEN: ${{ env.TOKEN }}
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/myredmine:latest .
          docker push docker.pkg.github.com/${{ github.repository }}/myredmine:latest

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Write your deployment script here
          # Example: ssh into production server and pull the latest Docker image
